package hello;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.IntByReference;
import hello.MyUser.ByValue;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>libcpp_lib_demo</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Libcpp_lib_demoLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "libcpp_lib_demo";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Libcpp_lib_demoLibrary.JNA_LIBRARY_NAME);
	public static final Libcpp_lib_demoLibrary INSTANCE = (Libcpp_lib_demoLibrary)Native.loadLibrary(Libcpp_lib_demoLibrary.JNA_LIBRARY_NAME, Libcpp_lib_demoLibrary.class);
	/**
	 * Original signature : <code>void hello()</code><br>
	 * <i>native declaration : library.h:6</i>
	 */
	void hello();
	/**
	 * Original signature : <code>void pp(int*, int)</code><br>
	 * <i>native declaration : library.h:7</i><br>
	 * @deprecated use the safer methods {@link #pp(java.nio.IntBuffer, int)} and {@link #pp(com.sun.jna.ptr.IntByReference, int)} instead
	 */
	@Deprecated 
	void pp(IntByReference arg, int len);
	/**
	 * Original signature : <code>void pp(int*, int)</code><br>
	 * <i>native declaration : library.h:7</i>
	 */
	void pp(IntBuffer arg, int len);
	/**
	 * Original signature : <code>MyUser echo(MyUser)</code><br>
	 * <i>native declaration : library.h:15</i>
	 */
	MyUser.ByValue echo(MyUser.ByValue user);
	/**
	 * Original signature : <code>MyUser* echoPoint(MyUser*)</code><br>
	 * <i>native declaration : library.h:17</i>
	 */
	MyUser echoPoint(MyUser user);
}
